name: "Feature Request"
description: "Suggest a new feature or improvement"
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for Purple Canary!
        Please provide detailed information about your feature request to help us understand your needs.
  - type: textarea
    id: problem-use-case
    attributes:
      label: "Problem / Use Case"
      description: "What problem does this feature solve? What use case does it address?"
      placeholder: "Example: Currently, Purple Canary doesn't provide real-time alerts when IoCs are detected. I need to be notified immediately when potential Pegasus spyware is detected."
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: "Proposed Solution"
      description: "Describe your proposed solution or how the feature should work"
      placeholder: "Example: Add support for email/Slack/webhook notifications when DNS queries match known IoCs. The feature could be configured through a config file with notification endpoints."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: "Have you considered alternative approaches?"
      placeholder: "Example: I considered using a separate monitoring script that parses Pi-hole logs, but having it integrated into Purple Canary would be more efficient."
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How important is this feature for your deployment?"
      options:
        - "Nice to have"
        - "Important"
        - "Critical for my deployment"
    validations:
      required: false
  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: "Willing to contribute"
      description: "I'm willing to help implement this feature"
      options:
        - label: "I'm willing to help implement this feature"
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Links to similar implementations, mockups, or other relevant information"
      placeholder: "Links to documentation, similar features in other projects, screenshots, etc."
    validations:
      required: false
